import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// Styles for the PDF (PDFs don't use Tailwind, they use CSS-in-JS)
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  header: { fontSize: 20, textAlign: 'center', marginBottom: 20, fontWeight: 'bold', textTransform: 'uppercase' },
  subHeader: { fontSize: 14, textAlign: 'center', marginBottom: 30 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 10, borderBottom: 1, paddingBottom: 5 },
  text: { fontSize: 12, marginBottom: 5 },
  bold: { fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 10, color: 'grey' }
});

interface PDFProps {
  invoiceNumber: string;
  clientName: string;
  buyerName: string;
  amount: string;
  interest: string;
  total: string;
}

export const InvoicePDF: React.FC<PDFProps> = ({ invoiceNumber, clientName, buyerName, amount, interest, total }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Before the Micro and Small Enterprise Facilitation Council</Text>
      <Text style={styles.subHeader}>Application under Section 18 of the MSMED Act, 2006</Text>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>1. Applicant Details</Text>
        <Text style={styles.text}><Text style={styles.bold}>Name:</Text> {clientName}</Text>
        <Text style={styles.text}><Text style={styles.bold}>Reference Invoice:</Text> {invoiceNumber}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>2. Respondent Details</Text>
        <Text style={styles.text}><Text style={styles.bold}>Name:</Text> {buyerName}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>3. Claim Summary</Text>
        <Text style={styles.text}>The applicant supplied goods/services to the respondent. As per the MSMED Act, payment was due within 45 days. The respondent has failed to make the payment, resulting in a delay.</Text>
        <Text style={styles.text}></Text>
        <Text style={styles.text}><Text style={styles.bold}>Principal Amount:</Text> Rs. {amount}</Text>
        <Text style={styles.text}><Text style={styles.bold}>Penal Interest (3x RBI Rate @ 19.5% p.a.):</Text> Rs. {interest}</Text>
        <Text style={styles.text}><Text style={styles.bold}>Total Claim Amount:</Text> Rs. {total}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>4. Prayer</Text>
        <Text style={styles.text}>The applicant prays that this Hon'ble Council may be pleased to direct the respondent to pay the total claim amount along with interest as calculated above.</Text>
      </View>

      <Text style={styles.footer}>Generated by Decree Legal Tech Platform</Text>
    </Page>
  </Document>
);